#*********************************************************************
#
#  (C) 2002 Justin Couch
#  http://www.vlc.com.au/~justin/
# 
# Makefile for the native code libraries
#
# Author: Justin Couch
# Version: $Revision: 1.2 $
#
#*********************************************************************

# The output library that we want to create
LIBRARY_LIST=image_decode

include ${PROJECT_ROOT}/make/Makefile.native
