#*********************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#*********************************************************************

PACKAGES = \
	 vlc.net.content.image \
	 vlc.net.content 

NODOC_PACKAGES = \

JARS =

JARS_3RDPARTY=

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = imageloader.jar

#*********************************************************************
#
# Javadoc
#
#*********************************************************************

WINDOWTITLE = 'VLC Content Handlers Specification'
DOCTITLE    = 'VLC ImageLoader API'
HEADER      = 'VLC ImageLoader API'
BOTTOM      = '<font size=2>Copyright &copy; 2000 - The Virtual Light Company \
		   <a href=\"http://www.vlc.com.au\">VLC</a></font>'

include $(PROJECT_ROOT)/make/Makefile.java 
