#
# Package makefile for the vlc.net.content directory
#

PACKAGE = vlc.net.content

SOURCE = ImageContentHandlerFactory.java \
         ImageFileNameMap.java

include ${PROJECT_ROOT}/make/Makefile.java
