#
# Makefile for producing the JAR file used by this library
#

# Describe every directory that you want included in the JAR file here.
# This is not recursive, so if you want parent directory and the 
# sub-directory, say so. These directories should not have '/' appended.
JAR_CONTENT= vlc/net/content \
  vlc/net/content/image

# Manifest file name. Stored in the src/java directory
MANIFEST=

include ${PROJECT_ROOT}/make/Makefile.jav
