#
# Package makefile for the vlc.net.content.image directory
#

PACKAGE = vlc.net.content.image

SOURCE = ImageBuffer.java \
         ImageDecoder.java \
         bmp.java \
         gif.java \
         jpeg.java \
         png.java \
         targa.java \
         tiff.java \
         x_portable_graymap.java \
         x_portable_pixmap.java

JNI_SOURCE=ImageDecoder.java

include ${PROJECT_ROOT}/make/Makefile.java
